Ada boost -- adaptive boosting combine multiple weak learner (with the help of decision stump)
               to find best result for a particular data

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("adaboost_student_performance.csv")

In [4]:
df

    StudyHours  Attendance  PreviousScore Passed
0          1.0          50             25     No
1          1.5          55             30     No
2          2.0          58             35     No
3          2.5          60             40     No
4          3.0          62             42     No
5          3.5          65             45     No
6          4.0          68             50     No
7          4.5          70             52    Yes
8          5.0          72             55     No
9          5.5          75             58    Yes
10         6.0          78             60    Yes
11         6.5          80             65    Yes
12         7.0          82             68    Yes
13         7.5          85             72    Yes
14         8.0          90             78    Yes
15         2.2          52             28     No
16         3.8          67             48     No
17         4.8          71             53    Yes
18         6.8          84             70    Yes
19         7.8          88             76    Yes

In [5]:
df.shape

(20, 4)

In [6]:
df.head()

   StudyHours  Attendance  PreviousScore Passed
0         1.0          50             25     No
1         1.5          55             30     No
2         2.0          58             35     No
3         2.5          60             40     No
4         3.0          62             42     No

In [7]:
df.tail()

    StudyHours  Attendance  PreviousScore Passed
15         2.2          52             28     No
16         3.8          67             48     No
17         4.8          71             53    Yes
18         6.8          84             70    Yes
19         7.8          88             76    Yes

In [8]:
df.isnull().sum()

StudyHours       0
Attendance       0
PreviousScore    0
Passed           0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)